### ISSUE TITLE
Server error rendering URLs with emoji

### ISSUE THREAD

**Issue by olivercoad** [check-face/facemorph.me#11]
Morphing with emoji as text value works fine, but if you try to load url that morphs with emoji, it just returns 500 server error.

```
This Serverless Function has crashed.
Your connection is working correctly.
Vercel is working correctly.
500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
```

https://facemorph.me/?from_value=%F0%9F%98%AD&to_value=%F0%9F%96%A5%E2%8C%A8

**Comment by olivercoad** [comment]
It looks like it's due to the server side rendering of the `Link` header for oembed including the target url, which includes
the URL encoded emoji in the query string. Apparently emoji in HTTP headers can have emoji, but maybe node doesn't support it.

```
[GET] /?from_value=%F0%9F%98%AD&to_value=%F0%9F%96%A5%E2%8C%A8
02:11:54:66
Can share? false
Got a request!
Success reading indexfile
2021-11-18T15:11:55.921Z	6af88f1d-52df-4bad-9324-349e6c85b0b8	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError [ERR_INVALID_CHAR]: Invalid character in header content [\"Link\"]","reason":{"errorType":"TypeError","errorMessage":"Invalid character in header content [\"Link\"]","code":"ERR_INVALID_CHAR","stack":["TypeError [ERR_INVALID_CHAR]: Invalid character in header content [\"Link\"]","    at ServerResponse.setHeader (_http_outgoing.js:533:3)","    at /var/task/deploy/api/server.js:77:285358","    at async Server.<anonymous> (/var/task/___vc/__helpers.js:813:13)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError [ERR_INVALID_CHAR]: Invalid character in header content [\"Link\"]","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:326:22)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}
Unknown application error occurred
```

OEmbed discovery should still be able to occur through the link element in the html header, so it should be fine to just remove
the http header.
